### ISSUE TITLE
[dunfell] bad gstreamer version

### ISSUE THREAD

**Issue by QB4-dev** [Freescale/meta-freescale-distro#32]
https://github.com/Freescale/meta-freescale-distro/blob/fbd12ff7e5f80a0e1fd71fa217d52a3c96659d16/conf/distro/include/fsl-base.inc#L65-L68

Current gstreamer version in meta-freescale is 1.16.imx
```
PREFERRED_VERSION_gstreamer1.0 = "1.16.imx"
PREFERRED_VERSION_gstreamer1.0-plugins-base = "1.16.imx"
PREFERRED_VERSION_gstreamer1.0-plugins-good = "1.16.imx"
PREFERRED_VERSION_gstreamer1.0-plugins-bad  = "1.16.imx"
```

**Comment by otavio** [comment]
Please prepare a PR.

**Comment by QB4-dev** [comment]
@otavio It's ready
https://github.com/Freescale/meta-freescale-distro/pull/33

**Comment by otavio** [comment]
One thing that is important is that you first fix this in master, then we can backport it to dunfell.

**Comment by QB4-dev** [comment]
This Pull Request should be Ok now:
https://github.com/Freescale/meta-freescale-distro/pull/34

Sorry for chaos - I'am still learning

**Comment by otavio** [comment]
No worries. I applied and backported the fix.

Thanks for the PR.
