### ISSUE TITLE
conf/distro/fslc* vs conf/distro/fsl*

### ISSUE THREAD

**Issue by dylad** [Freescale/meta-freescale-distro#45]
Hello

I was wondering if there is any reason to maintain both conf/distro/fslc* and conf/distro/fsl* files while content is the same for both ?

Regards,

**Comment by otavio** [comment]
It is not the same. 

- fsl*: uses the NXP components, such as GStreamer, Linux kernel, and U-Boot. It is very close to NXP releases
- fslc*: uses GStreamer mainline, Linux kernel mainline, NXP + stable releases, and U-Boot mainline.

So both are useful for different use cases.
