### ISSUE TITLE
imx-gpu-sdk build is broken due to missing assimp from upstream

### ISSUE THREAD

**Issue by zandrey** [Freescale/meta-freescale-distro#71]
Since OE-Core commit [`92719e01a9 ("assimp: Remove it")`](https://github.com/openembedded/openembedded-core/commit/92719e01a90f2a80f5cceb2f98a48c49f0c24f1c), _assimp_ package is dropped and removed from all layers.

This causes the `imx-gpu-sdk` package build to fail during parsing stage with following errors:
```
Nothing PROVIDES 'assimp' (but /work/yocto-master/meta-freescale-distro/recipes-graphics/imx-gpu-sdk/imx-gpu-sdk_5.7.1.bb DEPENDS on or otherwise requires it). Close matches:
      ssmtp

Runtime target 'imx-gpu-sdk' is unbuildable, removing...
    Missing or unbuildable dependency chain was: ['imx-gpu-sdk', 'assimp']

Runtime target 'imx-gpu-sdk' is unbuildable, removing...
    Missing or unbuildable dependency chain was: ['imx-gpu-sdk', 'assimp']

Runtime target 'packagegroup-fsl-tools-gpu' is unbuildable, removing...
    Missing or unbuildable dependency chain was: ['packagegroup-fsl-tools-gpu', 'imx-gpu-sdk', 'assimp']

Runtime target 'packagegroup-fsl-tools-gpu' is unbuildable, removing...
    Missing or unbuildable dependency chain was: ['packagegroup-fsl-tools-gpu', 'imx-gpu-sdk', 'assimp']
```

Recipe has been dropped upstream, as it appears to have several licensing-related issues and indicated that no OE-Core recipes are dependent on it.

As a potential solution here, this recipe can be taken into this layer, but I'm not sure is this is the right idea considering the information about licensing issues.

@thochstein Do you maybe aware of why GPU SDK does have a dependency on _assimp_ and if yes - can it be exchanged ot removed?

From the [conversation on OE-Core ML](https://lists.openembedded.org/g/openembedded-core/topic/85431030#155757), it seems that _Vulkan_ does not have a direct dependency on it, but I'm not sure if this applies to SDK in general.

-- andrey

**Comment by thochstein** [comment]
Thanks, @zandrey. I'm told that `assimp` is required. I'm looking at it to see if we can strip the folders with license issues.
